version: '3.4'

services:

  armyknife:
    build: .
    environment:
      - AWS_DB_HOST=http://dynamodb:8000
      - APP_HOST_FQDN=localhost
      - APP_HOST_PROTOCOL=http://
      - AWS_ACCESS_KEY_ID=dummy
      - AWS_SECRET_ACCESS_KEY=dummy
      - AWS_DB_PREFIX
      - AWS_DEFAULT_REGION=us-west-1
      - APP_BOT_SECRET
      - APP_BOT_ADMIN_ROOM
      - APP_BOT_TOKEN
      - APP_BOT_EMAIL
      - APP_OAUTH_ID
      - APP_OAUTH_KEY
    volumes:
      - .:/src
    ports:
      - 5000:5000

  dynamodb:
    image: deangiberson/aws-dynamodb-local
    command: -port 8000 -sharedDb
    ports:
      - 8000:8000
